# Generated by Django 3.1.3 on 2020-11-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="amout_of_upvotes",
            new_name="amount_of_upvotes",
        ),
    ]
