# Generated by Django 3.1.3 on 2020-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_board", "0003_auto_20201119_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(help_text="Share your opinion...", max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.URLField(
                help_text="Don't forget to provide a link", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(help_text="What's new?", max_length=200),
        ),
    ]
